name: Test Package Installation and Basic Functions

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
  # 当发布工作流触发时也运行测试
  workflow_call:

# 添加明确的权限限制
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false  # 防止凭证持久化

    # https://docs.astral.sh/uv/guides/integration/github/#syncing-and-running
    - name: Install uv
      uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v5
      with:
        enable-cache: true

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      run: uv run pytest tests
